#!/bin/sh
#
# Create a skeleton Debian package changelog file. Inspired by 
# https://github.com/tvheadend/tvheadend/blob/master/support/changelog
#

# Arguments
CHANGELOG=$1
DIST=$2
VER=$3
REVISION=$4

# Defaults
[ -z "$CHANGELOG"     ] && CHANGELOG=$(dirname "$0")/../debian/changelog
[ -z "$DEBEMAIL"      ] && DEBEMAIL="dummy@example.com"
[ -z "$DEBFULLNAME"   ] && DEBFULLNAME="Minisatip maintainers"
[ -z "$DIST"          ] && DIST=unstable

# Output
NOW=$(date -R)
echo >"${CHANGELOG}"  "minisatip (${VER}-${REVISION}) ${DIST}; urgency=low"
echo >>"${CHANGELOG}"
echo >>"${CHANGELOG}" "  * The full changelog(s) can be found at "
echo >>"${CHANGELOG}" "    https://github.com/catalinii/minisatip/releases"
echo >>"${CHANGELOG}" "    https://github.com/catalinii/minisatip"
echo >>"${CHANGELOG}"
echo >>"${CHANGELOG}" " -- ${DEBFULLNAME} <${DEBEMAIL}>  ${NOW}"
