#!/bin/sh

set -e

case "$1" in
    configure)
    if ! getent passwd minisatip 1>/dev/null; then
        adduser --quiet --system --group --disabled-password --system \
        --home /var/lib/minisatip --shell /bin/sh minisatip
#        mkdir -p /var/lib/minisatip
#        chown minisatip:minisatip /var/lib/minisatip
    fi

    if ! dpkg-statoverride --list /var/lib/minisatip >/dev/null 2>&1
    then
        dpkg-statoverride --update --add minisatip minisatip 755 /var/lib/minisatip
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
